name: docs_{{cookiecutter.project_name}}
channels:
{% if cookiecutter.dependency_source == 'Prefer conda-forge with pip fallback' %}
  - conda-forge
{% endif %}
  - defaults
dependencies:
    # Base depends
  - python
  - pip
  {% if cookiecutter.dependency_source == 'Prefer conda-forge with pip fallback' %}
  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-copybutton
{% endif %}

{% if cookiecutter.dependency_source == 'Prefer default anaconda channel with pip fallback' %}
  # Pip-only installs
  - pip:
    - -e ../
    - pydata-sphinx-theme
    - sphinx-design
    - sphinx-copybutton
{% else %}

    # Pip-only installs
  - pip:
    - -e ../
{% endif %}
